#!/usr/bin/env sh
# shellcheck shell=sh
# - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202303022155-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@License          :  WTFPL
# @@ReadME           :  README.md
# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
# @@Created          :  Thursday, Mar 02, 2023 21:54 EDT
# @@File             :  00-default.mac
# @@Description      :  Default macOS shell aliases for system, sudo, git, ssh, and utility commands
# @@Changelog        :  Standardized header block to the new @@ template
# @@TODO             :
# @@Other            :
# @@Resource         :
# @@Terminal App     :  no
# @@sudo/root        :  yes
# @@Template         :  shell/sh
# - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=SC1001,SC1003,SC2001,SC2003,SC2016,SC2031,SC2090,SC2115,SC2120,SC2155,SC2199,SC2229,SC2317,SC2329
# - - - - - - - - - - - - - - - - - - - - - - - -
VERSION="202303022155-git"
# System Aliases
command -v gdate >/dev/null 2>&1 && alias date='gdate '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
alias q='exit '
alias :q='exit '
alias :q!='exit '
alias :w='if [ -n "$ZSH_VERSION" ]; then fc -AI; else history -a; fi '
alias c='clear '
alias ch='if [ -n "$ZSH_VERSION" ]; then fc -p; else history -c &>/dev/null && history -w &>/dev/null; fi '
alias g='git '
alias m='man '
alias map='xargs -n1 '
alias n='npm '
alias path='printf "%b\n" "${PATH//:/\\n}" '
alias t='tmux '
alias bashrc='clear && source ~/.bashrc '
alias inputrc='bind -f ~/.inputrc '
alias tailf='tail -f '
alias mount='mount -l '
alias h='history '
alias j='jobs -l '
alias nowtime='date +"%T" '
alias nowdate='date +"%m-%d-%Y" '
alias wget='wget -c '
alias df='df -H '
alias du='du -ch '
alias setverfile='setver --file '
alias userlist='cut -d: -f1 /etc/passwd '
alias muttsync='mailsync '
alias mutt='neomutt '
alias sort='LC_ALL=C sort '
alias uniq='LC_ALL=C uniq '
alias lynx='lynx -cfg=$HOME/.config/lynx/lynx.cfg -lss=$HOME/.config/lynx/lynx.lss '
alias grep='grep --color=auto '
alias egrep='grep -E --color=auto '
alias fgrep='grep -F --color=auto '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# sudo commands
alias sudo='\sudo --preserve-env=PATH '
alias svi='\sudo vim '
alias adb='\sudo adb '
alias npmg='\sudo npm -g '
alias netstat='sudo netstat '
alias fastboot='sudo fastboot '
alias ipconfig='sudo ifconfig '
alias systemctl='sudo systemctl '
alias ports='sudo netstat -taupln | grep --color=auto LISTEN '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ssh aliases
[ -n "$DISPLAY" ] && alias ssh='ssh -X' || alias ssh='ssh '
[ -n "$DISPLAY" ] && alias sshq='ssh -qX' || alias ssh='ssh -q '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
command -v gls >/dev/null 2>&1 && alias ll='gls -l --color=auto '
command -v gls >/dev/null 2>&1 && alias l.='gls -LA --color=auto '
command -v gls >/dev/null 2>&1 && alias ls='gls --color=auto '
command -v gls >/dev/null 2>&1 && alias la='gls -A --color=auto '
command -v gls >/dev/null 2>&1 && alias lla='gls -lA --color=auto  '
command -v gls >/dev/null 2>&1 && alias dir='gls -D --color=auto  '
command -v greadlink >/dev/null 2>&1 && alias readlink='greadlink  '
command -v gbasename >/dev/null 2>&1 && alias basename='gbasename  '
command -v grealpath >/dev/null 2>&1 && alias realpath='grealpath  '
command -v gdircolors >/dev/null 2>&1 && alias dircolors='gdircolors  '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# CD Aliases
alias ~='builtin cd ~'
alias ..='builtin cd ..'
alias ...='builtin cd ../..'
alias ....='builtin cd ../../..'
alias .....='builtin cd ../../../..'
alias cd..='builtin cd ..'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#Set vim
[ -f "/usr/local/bin/vim" ] && alias vi='/usr/local/bin/vim '
[ -f "/usr/local/bin/vim" ] && alias vim='/usr/local/bin/vim '
[ -f "/usr/local/bin/vim" ] && alias vis='/usr/local/bin/vim +set si '
[ -f "/usr/local/bin/vim" ] && alias svi='sudo /usr/local/bin/vim '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#Set neovim
[ -f "/usr/local/bin/nvim" ] && alias nvim='/usr/local/bin/nvim -u $HOME/.config/neovim/init.vim '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#Set docker
[ -f "$(command -v docker)" ] && alias docker='sudo docker '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Empty trash.
alias empty-trash='sudo rm -frv /Volumes/*/.Trashes; sudo rm -frv ~/.Trash; sudo rm -frv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* "delete from LSQuarantineEvent" '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Hide/show icons.
alias desktop-icons-show='defaults write com.apple.finder CreateDesktop -bool true && killall Finder '
alias desktop-icons-hide='defaults write com.apple.finder CreateDesktop -bool false && killall Finder '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Flush dns
alias flushdns='dscacheutil -flushcache && killall -HUP mDNSResponder '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Lock Screen
alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Open command
alias o='open '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# youtube-dl
command -v youtube-dl >/dev/null 2>&1 && alias nightcorea='ytda nightcorea '
command -v youtube-dl >/dev/null 2>&1 && alias nightcorev='ytda nightcorev '
command -v youtube-dl >/dev/null 2>&1 && alias ytv-best='ytda ytv '
command -v youtube-dl >/dev/null 2>&1 && alias yta-aac='ytda aac '
command -v youtube-dl >/dev/null 2>&1 && alias yta-best='ytda yta '
command -v youtube-dl >/dev/null 2>&1 && alias yta-flac='ytda flac '
command -v youtube-dl >/dev/null 2>&1 && alias yta-m4a='ytda m4a '
command -v youtube-dl >/dev/null 2>&1 && alias yta-mp3='ytda mp3 '
command -v youtube-dl >/dev/null 2>&1 && alias yta-opus='ytda opus '
command -v youtube-dl >/dev/null 2>&1 && alias yta-vorbis='ytda vorbis '
command -v youtube-dl >/dev/null 2>&1 && alias yta-wav='ytda wav '
command -v youtube-dl >/dev/null 2>&1 && alias streamyt='ytstream '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Media
command -v castero >/dev/null 2>&1 && alias podcasts='castero '
command -v spotifyd >/dev/null 2>&1 && alias spotify='spotifyd '
command -v pianobar >/dev/null 2>&1 && alias pandora='pianobar '
command -v tizonia >/dev/null 2>&1 && alias cloudplayer='tizonia '
command -v youtube-viewer >/dev/null 2>&1 && alias youtube='youtube-viewer '
if command -v mpc >/dev/null 2>&1; then
  [ -z "$MPDSERVER" ] && alias mpc='mpc ' || alias mpc='mpc -h "$MPDSERVER" '
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# list functions
alias list-my-functions='if [ -n "$ZSH_VERSION" ]; then functions | less; else typeset -F | less; fi '
alias list-my-aliases='alias | less '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#Fun alias
alias tw='rainbowstream -iot '
alias mylatlong='mylocation | grep -E "LAT | LON" '
alias emj='emojis '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# other

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Import global aliases
[ -f "$HOME/.config/misc/shell/aliases/00-aliases.sh" ] && . "$HOME/.config/misc/shell/aliases/00-aliases.sh"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
true
