#!/usr/bin/env zsh
export ZSH="$HOME/.local/share/zsh/oh-my-zsh"
export ZSH_CUSTOM="$HOME/.local/share/zsh/oh-my-zsh/custom"
export ZSH_CACHEDIR="$HOME/.cache/oh-my-zsh"
export ZPLUG_HOME="$HOME/.local/share/zsh/zplug" 
export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$HOME/.cache/zhistory"
export SAVEHIST=5000
export HISTSIZE=2000
